Framework.Web/Controllers/WeChatController.cs
using Framework.Entity;
using Framework.Interfaces;
using Framework.Utility.Enums;
using Framework.Utility.Models;
using Framework.Web.App_Start;
using Framework.WeChat;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Framework.Utility.Tools;

namespace Framework.Web.Controllers
{
    /// <summary>
    /// 微信公众号控制器
    /// </summary>
    public class WeChatController : BaseController<IWeChat>
    {
        //
        // GET: /WeChat/

        /// <summary>
        /// 获取微信列表数据视图
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(PageInfo pageInfo, int? iType)
        {
            if (Request.HttpMethod.ToUpper() == MethodType.GET)
            {
                return View();
            }
            else
            {
                return Content(Manager.GetList(pageInfo, iType));
            }
        }

        /// <summary>
        /// 获取微信公众号列表
        /// </summary>
        /// <returns></returns>
        public ActionResult GetList()
        {
            var data = Manager.GetList();
            return Content(data);
        }

        /// <summary>
        /// 添加微信公众号
        /// </summary>
        /// <param name="WeChat"></param>
        /// <returns></returns>
        public ActionResult Add(ES_WeChat WeChat)
        {
            if (Request.HttpMethod.ToUpper() == MethodType.GET)
            {
                return View();
            }
            else
            {
                if (Manager.Insert(WeChat) > 0)
                    result.success = true;
                return Json(result);
            }
        }

        /// <summary>
        /// 编辑微信公众号
        /// </summary>
        /// <param name="WeChat"></param>
        /// <returns></returns>
        public ActionResult Edit(ES_WeChat WeChat)
        {
            if (Request.HttpMethod.ToUpper() == MethodType.GET)
            {
                return View(Manager.Get(WeChat.ID));
            }
            else
            {
                if (Manager.Update(WeChat) > 0)
                    result.success = true;
                return Json(result);
            }
        }

        /// <summary>
        /// 删除微信公众号
        /// </summary>
        /// <param name="WeChat"></param>
        /// <returns></returns>
        public ActionResult Cancel(string WeChatIds)
        {
            if (Manager.Cancel(WeChatIds) > 0)
                result.success = true;
            return Json(result);
        }

        /// <summary>
        /// 成为开发者
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult Developer(Guid ID)
        {
            if (Manager.Developer(ID) > 0)
                result.success = true;
            return Json(result);
        }

        /// <summary>
        /// 创建菜单
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateMenu()
        {
            var weChat = Manager.GetDeveloper();//获取开发者微信公众号
            //获取公众号的所有菜单
            var menuList = GetImpl<IWeChatMenu>().GetMenuByWeChat(weChat.ID.ToString());
            //二级菜单
            var childList = menuList.Where(m => string.IsNullOrEmpty(m.sParentMenuId) == false).ToList();
            var body = new List<dynamic>();
            foreach(var item in menuList)
            {
                if (string.IsNullOrEmpty(item.sParentMenuId))
                {//一级菜单
                    dynamic obj = new System.Dynamic.ExpandoObject();
                    obj.name = item.sMenuName;
                    obj.type = item.sTiggerType;
                    obj.key = item.sKey;
                    obj.url = item.sUrl;
                    var obj_sub = new List<dynamic>();
                    foreach(var child in childList)
                    {
                        if (item.ID.ToString() == child.sParentMenuId)
                        {
                            obj_sub.Add(new
                            {
                                name = child.sMenuName,
                                type = child.sTiggerType,
                                key = child.sKey,
                                url = child.sUrl
                            });
                        }
                    }
                    obj.sub_button = obj_sub;
                    body.Add(obj);
                }
            }
            string bodyStr = JsonHelper.ToJsonString(new { button= body });
            IWeChatRequest request = new CreateAutoMenuRequest();
            CreateAutoMenuModel model = new CreateAutoMenuModel();
            model.sAppId = weChat.sAppId;
            model.sAppSecret = weChat.sAppSecret;
            model.sBody = bodyStr;
            CreateAutoMenuRespone respone =request.Execute<CreateAutoMenuRespone>(model);
            if (respone.errcode == 0)
            {
                result.success = true;
                result.info = "菜单创建成功";
            }
            else
                result.info = respone.errcode.ToString() + respone.errmsg;
            return Json(result);
        }
    }
}

Framework.Web/Controllers/WeChatKeyWordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Framework.Utility.Enums;
using Framework.Web.App_Start;
using Framework.Interfaces;
using Framework.Utility.Models;
using Framework.Entity;

namespace Framework.Web.Controllers
{
    /// <summary>
    /// 微信关键回复
    /// </summary>
    public class WeChatKeyWordController : BaseController<IWeChatKeyWord>
    {
        //
        // GET: /WeChatKeyWord/

        /// <summary>
        /// 微信关键字视图列表
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(PageInfo pageInfo,string sWeChatId)
        {
            if (Request.HttpMethod.ToUpper() == MethodType.GET)
            {
                return View();
            }
            else
            {
                return Content(Manager.GetList(pageInfo, sWeChatId));
            }
        }

        /// <summary>
        /// 添加关键字
        /// </summary>
        /// <param name="KeyWord"></param>
        /// <returns></returns>
        public ActionResult Add(ES_WeChatKeyWord KeyWord)
        {
            if (Request.HttpMethod.ToUpper() == MethodType.GET)
            {
                return View();
            }
            else
            {
                if (Manager.Insert(KeyWord) > 0)
                    result.success = true;
                return Json(result);
            }
        }

        /// <summary>
        /// 编辑关键字
        /// </summary>
        /// <param name="KeyWord"></param>
        /// <returns></returns>
        public ActionResult Edit(ES_WeChatKeyWord KeyWord)
        {
            if (Request.HttpMethod.ToUpper() == MethodType.GET)
            {
                return View(Manager.Get(KeyWord.ID));
            }
            else
            {
                if (Manager.Update(KeyWord) > 0)
                    result.success = true;
                return Json(result);
            }
        }

        /// <summary>
        /// 删除关键字
        /// </summary>
        /// <returns></returns>
        public ActionResult Cancel(string Ids)
        {
            if (Manager.Cancel(Ids) > 0)
                result.success = true;
            return Json(result);
        }


    }
}

Framework.Web/Views/WeChatKeyWord/Add.cshtml
@{
    ViewBag.Title = "添加关键字";
}
<form id="dataForm">
    <table class="gridtable">
        <tr>
            <td>选择公众号</td>
            <td>
               <input class="easyui-combobox" id="sWeChatId" name="sWeChatId"
                       data-options="valueField:'ID',textField:'sWeChatName',width:240,panelHeight:'auto',url:'@Url.Action("GetList","WeChat")'" />
            </td>
        </tr>
        <tr>
            <td>回复类型</td>
            <td>
               @Html.Partial("~/Views/Shared/_DictionaryList.cshtml", new Framework.Utility.Models.ItemDictionary()
                        { Name = "iRePlyType", Width = 240, Type = "WeChatMsgType", Required = "true" })
            </td>
        </tr>
        <tr>
            <td>是否启用</td>
            <td>
                <input id="bIsOpen" class="easyui-switchbutton" data-options="onText:'启用',offText:'禁用'">
                <input type="hidden" name="bIsOpen" />
            </td>
        </tr>
        <tr>
            <td>关键字名称</td>
            <td>
                <input class="easyui-textbox" name="sKeyWordName" data-options="required:true,width:240">
                <input type="hidden" name="bIsOpen" />
            </td>
        </tr>
        <tr>
            <td>图文消息</td>
            <td>
                <input class="easyui-textbox" name="sWeChatNewsName" data-options="width:240,readonly:true">
                <a class="easyui-linkbutton" data-options="iconCls:'icon-file'">选择图文</a>
                <input type="hidden" name="sWeChatNewsNameId" />
            </td>
        </tr>
        <tr>
            <td>文本消息</td>
            <td>
                <textarea name="sContent" style="height:100px;width:240px;"></textarea>
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">
    $(function () {
        $('#bIsOpen').switchbutton({
            onChange: function (checked) {
                if (checked)
                    $('input[name=bIsOpen]').val(true);
                else
                    $('input[name=bIsOpen]').val(false);
            }
        });
        
        //公众号的赋值
        $('#sWeChatId').combobox({
            onLoadSuccess: function () {
                var value = sessionStorage.getItem("selectWeChatId");   
                $('#sWeChatId').combobox("setValue", value);
            }
        });
    });
</script>

Framework.Web/Views/WeChatKeyWord/Edit.cshtml
@{
    ViewBag.Title = "编辑关键字";
}
@model Framework.Entity.ES_WeChatKeyWord
<form id="dataForm">
    <input type="hidden" name="ID" value="@Model.ID" />
    <input type="hidden" name="dInsertTime" value="@Model.dInsertTime" />
    <table class="gridtable">
        <tr>
            <td>选择公众号</td>
            <td>
                <input class="easyui-combobox" id="sWeChatId" name="sWeChatId" value="@Model.sWeChatId"
                       data-options="valueField:'ID',textField:'sWeChatName',width:240,panelHeight:'auto',url:'@Url.Action("GetList","WeChat")'" />
            </td>
        </tr>
        <tr>
            <td>回复类型</td>
            <td>
                @Html.Partial("~/Views/Shared/_DictionaryList.cshtml", new Framework.Utility.Models.ItemDictionary()
          { Name = "iRePlyType", Width = 240, Type = "WeChatMsgType", Required = "true",Value=Model.iRePlyType })
            </td>
        </tr>
        <tr>
            <td>是否启用</td>
            <td>
                <input id="bIsOpen" class="easyui-switchbutton" data-options="onText:'启用',offText:'禁用'">
                <input type="hidden" name="bIsOpen" value="@Model.bIsOpen" />
            </td>
        </tr>
        <tr>
            <td>关键字名称</td>
            <td>
                <input class="easyui-textbox" name="sKeyWordName" data-options="required:true,width:240" value="@Model.sKeyWordName">
            </td>
        </tr>
        <tr>
            <td>图文消息</td>
            <td>
                <input class="easyui-textbox" name="sWeChatNewsName" data-options="width:240,readonly:true" value="@Model.sWeChatNewsNameId">
                <a class="easyui-linkbutton" data-options="iconCls:'icon-file'">选择图文</a>
                <input type="hidden" name="sWeChatNewsNameId" value="@Model.sWeChatNewsNameId" />
            </td>
        </tr>
        <tr>
            <td>文本消息</td>
            <td>
                <textarea name="sContent" style="height:100px;width:240px;">@Model.sContent</textarea>
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">
    $('#bIsOpen').switchbutton({
        onChange: function (checked) {
            if (checked)
                $('input[name=bIsOpen]').val(true);
            else
                $('input[name=bIsOpen]').val(false);
        }
    });

    //开关的默认值设置
    var bIsOpen = '@Model.bIsOpen'.toLowerCase();
    if (bIsOpen == 'true')
        $('#bIsOpen').switchbutton('check');
    else
        $('#bIsOpen').switchbutton('uncheck');
</script>

Framework.Web/Views/WeChatKeyWord/Index.cshtml
@{
    ViewBag.Title = "微信关键字视图列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table id="weChatKeyWord"></table>
<div id="weChatKeyWord_toolbar" style="padding:5px;">
    <form id="searchForm">
        <div style="margin-bottom:5px;">
            <span class="label">选择公众号</span>
            <input class="easyui-combobox" name="sWeChatId"
                   data-options="valueField:'ID',textField:'sWeChatName',width:180,panelHeight:'auto',url:'@Url.Action("GetList","WeChat")'" />
            <span class="label">模糊查询</span>
            <input class="easyui-textbox" name="keyword" data-options="iconCls:'icon-search',prompt:'关键字'">
            <a class="easyui-linkbutton" data-mark="search" data-options="width:60">查 询</a>
        </div>
    </form>
    @Html.Partial("~/Views/Shared/_Btn.cshtml")
</div>
<script type="text/javascript">
    $(function () {
        var grid = $('#weChatKeyWord');
        var toolbar = '#weChatKeyWord_toolbar';

        //所有按钮事件的绑定
        $(toolbar).on("click", 'a', function () {
            eui.dialogArgs.title = $(this).text();
            eui.dialogArgs.url = $(this).attr("data-url");
            eui.dialogArgs.width = 480;
            eui.dialogArgs.height = 380;
            switch ($(this).attr("data-mark")) {
                case 'search':
                    var params = eui.serializeJson(eui.searchForm);
                    sessionStorage.setItem("selectWeChatId", params.sWeChatId);
                    grid.datagrid({ queryParams: params });
                    break;
                case 'add':
                    eui.dialogArgs.callback = operate;
                    eui.dialog(eui.dialogArgs);
                    break;
                case 'edit':
                    var selected = grid.treegrid('getSelections');
                    if (selected.length == 1) {
                        eui.dialogArgs.url += "?ID=" + selected[0].ID;
                        eui.dialogArgs.callback = operate;
                        eui.dialog(eui.dialogArgs);
                    }
                    else
                        eui.alert("请选择一条数据操作");
                    break;
                case 'cancel':
                    cancel();
                    break;
            }
        });

        //新增编辑操作
        function operate() {
            if ($(eui.form).form("validate")) {
                eui.button.disable();
                eui.commitArgs.url = eui.dialogArgs.url;
                eui.commitArgs.data = $(eui.form).serialize();
                eui.commitArgs.success = function (r) {
                    eui.alert(r.info);
                    grid.datagrid('reload');
                }
                eui.commit(eui.commitArgs);
            }
        }

        //删除操作
        function cancel() {
            var selected = grid.datagrid('getSelections');
            if (selected.length > 0) {
                eui.confirm("确认要删除所选择的数据", function () {
                    var Ids = [];
                    $(selected).each(function () { Ids.push(this.ID) });
                    eui.commitArgs.url = eui.dialogArgs.url;
                    eui.commitArgs.data = { Ids: Ids.join() };
                    eui.commitArgs.success = function (r) {
                        grid.datagrid('reload');
                        grid.datagrid("clearSelections");
                        eui.alert(r.info);
                    }
                    eui.commit(eui.commitArgs);
                });
            }
            else
                eui.alert("请选择一条数据操作");
        }


        //列表数据的绑定
        grid.datagrid({
            url:'@Url.Action("Index")',
            toolbar: toolbar,
            sortOrder: 'desc',
            sortName: 'dInsertTime',
            singleSelect: false,
            columns: [[
                { field: 'ID',align: 'center', checkbox:true },
                { field: 'sKeyWordName', title: '关键字', align: 'center', width: 150 },
                {
                    field: 'iRePlyType', title: '回复类型', align: 'center', width: 80, formatter: function (value) {
                        if (value == 1) return "文本";
                        if (value == 2) return "图文";
                    }},
                {
                    field: 'bIsOpen', title: '是否启用', align: 'center', width: 80, formatter: function (value) {
                        return value == true ? "<span  style='color:green'>启用</span>" : "<span style='color:red'>禁用</span>";
                    }
                },
                { field: 'dUpdateTime', title: '最近更新时间', align: 'center', width: 120 },
                { field: 'dInsertTime', title: '添加时间', align: 'center', width: 120 },
            ]],
            onDblClickRow: function (index, row) {
                eui.dialogArgs.width = 480;
                eui.dialogArgs.height = 380;
                eui.dialogArgs.title = "编辑关键字";
                eui.dialogArgs.url = '@Url.Action("Edit")';
                eui.dialogArgs.url += "?ID=" + row.ID;
                eui.dialogArgs.callback = operate;
                eui.dialog(eui.dialogArgs);
            }
        });
    });
</script>